project:
  type: website

website:
  title: "Course Template"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - text: "Notebooks"
        menu:
          - text: "Explore GWAS sumstats"
            href: 00_explore_gwas_sumstats.ipynb
          - text: "Fine-mapping"
            href: 01_finemapping.ipynb
          - text: "Magma prepare input"
            href: 02_magma_prepare_input.ipynb
          - text: "magma_snp_annotation"
            href: 03_magma_snp_annotation.ipynb
          - text: "magma_gene_analysis"
            href: 04_magma_gene_analysis.ipynb
          - text: "magma_geneset_analysis"
            href: 05_magma_geneset_analysis.ipynb
          - text: "FLAMES"
            href: 06_flames.ipynb
          - text: "Run scdrs"
            href: 07_run_scdrs.ipynb
          - text: "analyse results scdrs"
            href: 08_analyse_results_scdrs.ipynb
          - text: "SNP based heritability"
            href: 09_SNP_based_heritability.ipynb
          - text: "genetic correlation"
            href: 10_genetic_correlation.ipynb
    right: 
      - icon: github
        href: https://github.com/SamueleSoraggi/post-gwas-phd-course
        aria-label: GitHub
      

format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
    code-fold: true
#    include-in-header: resources/bioschema.html