project:
  type: website

website:
  title: "Course Template"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - text: "Notebooks"
        menu:
          - text: "Explore GWAS sumstats"
            href: Notebooks/00_explore_gwas_sumstats.ipynb
          - text: "Fine mapping"
            href: Notebooks/01_finemapping.ipynb
          - text: "From variants to genes and tissues"
            href: Notebooks/02_magma_workflow.ipynb
          - text: "FLAMES"
            href: Notebooks/03_flames.ipynb
          - text: "Run scdrs"
            href: Notebooks/04_run_scdrs.ipynb
          - text: "analyse results scdrs"
            href: Notebooks/05_analyse_results_scdrs.ipynb
          - text: "SNP based heritability"
            href: Notebooks/06_SNP_based_heritability.ipynb
          - text: "genetic correlation"
            href: Notebooks/07_genetic_correlation.ipynb
    right: 
      - icon: github
        href: https://github.com/SamueleSoraggi/post-gwas-phd-course
        aria-label: GitHub
      

format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
    code-fold: true
#    include-in-header: resources/bioschema.html
