#!/usr/bin/env bash
# Purpose: Real SBayesRC genome-wide fine-mapping for the ADHD GWAS, producing the
#          per-locus .snpRes the fine-mapping exercise (Block 4) reads. Replaces the
#          softmax mock generated by prepare_data.R.
# Author:  course materials
# Date:    2026-06-17
# Run on:  HPC ONLY (needs gctb + the ~tens-of-GB UKB LD eigen reference, and reads
#          the raw DUA-bound ADHD sumstats). Do not run on the laptop.
#
# Prereqs (edit the paths below):
#   - gctb >= 2.5 on PATH
#   - UKB EUR 13M eigen LD reference (ukbEUR_13M_FullLDM) + ref_b37_1588blocks.pos
#     and the 96-annotation file, from https://gctbhub.cloud.edu.au (Download).
#   - Raw ADHD daner sumstats (ADHD2022_iPSYCH_deCODE_PGC.meta).
#
# Verified CLI (GCTB SBayesRC tutorial, 2026-06-17):
#   step 1  gctb --ldm <FullLDM> --gwas-summary <ma> --make-ldm-eigen --out <eigen>
#   step 2  gctb --gwfm RC --ldm-eigen <eigen> --gwas-summary <ma> --annot <annot> --out <prefix>
# Output: <prefix>.snpRes (cols Index Name Chrom Position A1 A2 A1Frq A1Effect SE
#         VarExplained PEP PIP GelmanRubin_R), plus .parRes .lcs .gcs .mcmcsamples.
set -euo pipefail

# EDIT THESE
GCTB=${GCTB:-gctb}
LDM_FULL=${LDM_FULL:-/path/to/ukbEUR_13M_FullLDM}     # the downloaded FullLDM prefix
ANNOT=${ANNOT:-/path/to/annot_13M_96.txt}             # 96-annotation file (matches 13M)
RAW_GWAS=${RAW_GWAS:-/path/to/ADHD2022_iPSYCH_deCODE_PGC.meta}
N_EFF=${N_EFF:-51568}                                 # Demontis 2023 effective N
THREADS=${THREADS:-16}

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SESSION_DIR="$(dirname "$HERE")"
WORK=${WORK:-$HERE/work}                               # scratch for intermediates
LOCUS_SUMSTATS="$SESSION_DIR/data/locus1_clean/sumstats.tsv"
OUT_PRECOMP="$SESSION_DIR/data/sbayesrc_precomputed"
mkdir -p "$WORK" "$OUT_PRECOMP"

echo "[1/4] daner -> .ma"
Rscript "$HERE/make_ma.R" "$RAW_GWAS" "$WORK/adhd.ma" "$N_EFF"

echo "[2/4] eigen-decomposition matched to the GWAS SNPs"
"$GCTB" --ldm "$LDM_FULL" --gwas-summary "$WORK/adhd.ma" \
        --make-ldm-eigen --thread "$THREADS" --out "$WORK/matched_ldm"

echo "[3/4] genome-wide SBayesRC (--gwfm RC)"
"$GCTB" --gwfm RC --ldm-eigen "$WORK/matched_ldm" --gwas-summary "$WORK/adhd.ma" \
        --annot "$ANNOT" --thread "$THREADS" --out "$WORK/adhd_sbrc"

echo "[4/4] subset to SORCS3 locus -> exercise schema"
Rscript "$HERE/subset_locus.R" \
        "$WORK/adhd_sbrc.snpRes" "$LOCUS_SUMSTATS" "$OUT_PRECOMP/locus1.snpRes"
cp -f "$WORK/adhd_sbrc.parRes" "$OUT_PRECOMP/locus1.parRes"

echo "Done. Real SBayesRC results in $OUT_PRECOMP/ (commit locus1.snpRes/.parRes; they are not under the DUA)."
